[FEAT] #94 : Scroll Back To Top Button
piyushgarg-dev/piyushgargdev-nextjs pull request #103
Opened 2023-06-09 05:32 UTC by krcpr007

## What does this PR do?

We reach the last page of the site i.e., the Contact page, again we need to scroll to get back to the Home page. Now there is an arrow icon after clicking that icon you will smoothly go back to the top of the page.
**The icon is not added to the right side because a contact form component will be made at that place.**

Fixes #94 
![image](https://github.com/piyushgarg-dev/piyushgargdev-nextjs/assets/80947662/22dcc7ab-7e40-4f30-8476-54dd58583585)

## Type of change

- New feature (non-breaking change which adds functionality)

## How should this be tested?
1. Go to the footer or bottom of the page then you can see a green color arrow icon click on that icon you will smoothly go back to the top of the page.

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

2023-06-09 09:24 UTC, piyushgarg-dev requested changes

2023-06-09 09:38 UTC, krcpr007 commented on components/UI/Contact.jsx
> +              <button onClick={handleScrollToTop}>
Sure!!

2023-06-09 12:34 UTC, TheMohit2003 reviewed
The svg seems a bit smaller . Can you increase its size ?

2023-06-12 03:07 UTC, TheMohit2003 commented
Hey @krcpr007 , pull the codes from this repo and try to resolve merge conflicts . To learn more on them , watch this [video](https://www.youtube.com/watch?v=l03tGz4pXoQ).

2024-10-30 14:33 UTC, closed without merging